name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-22.04

    env:
      nix: nix develop .#ci --command

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - name: Prepare CI environment
      run: nix develop .#ci
    - name: CMake generate
      run: $nix cmake -DCMAKE_BUILD_TYPE=Release -B build
    - name: CMake build
      run: $nix cmake --build build -j $(nproc)
    - name: CTest
      run: $nix ctest --test-dir build/tests
