name: cmake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install nlohmann-json3-dev libeigen3-dev
    - name: mkdir build
      run: mkdir build
    - name: CMake generate 
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build
    - name: CMake build
      run: cmake --build build -- -j $(nproc)
    - name: CTest
      run: ctest --test-dir build/tests
