name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Update package repositories
      run: sudo apt update
    - name: install dependencies
      run: sudo apt install -y cmake nlohmann-json3-dev libeigen3-dev
    - name: mkdir build
      run: mkdir build
    - name: CMake generate 
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build
    - name: CMake build
      run: cmake --build build -- -j $(nproc)
    - name: CTest
      run: ctest --test-dir build/tests
